language: php

php:
  - hhvm
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml
  - "composer require nikic/fast-route:*@dev && php bench.php"
