language: php

php:
  - hhvm
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml
  - "composer require \"nikic/fast-route : *@dev\""
  - php bench.php
