language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml

  - composer require "aura/router":"3.0.*@dev"
  - composer require "zendframework/zend-diactoros"
  - composer require "symfony/routing":"3.0.*@dev"
  - composer require "nikic/fast-route":"1.0.*@dev"

  - php bench.php
