language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml
  - vendor/bin/psalm

  - composer require "nikic/fast-route":"1.0.*@dev"

  - php bench.php
